### ISSUE TITLE
An "is defined" statement needed in ansible-filebeat/tasks/config.yml

### ISSUE THREAD

**Issue by M-Golyani** [wazuh/wazuh-ansible#175] opened 2019-04-29 14:38 UTC
Hi there :)
In this file:

https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-filebeat/tasks/config.yml

At line 16, there is a condition to check whether filebeat_ssl_key_file is defined or not:

`- name: Ensure Filebeat SSL key pair directory exists.`
`  file:`
`    path: "{{ filebeat_ssl_dir }}"`
`    state: directory`
`  when: filebeat_ssl_key_file`
`  tags: configure`

This check fails with this error:

> FAILED! => {"msg": "The conditional check 'filebeat_ssl_key_file' failed. The error was: error while evaluating conditional (filebeat_ssl_key_file): 'filebeat' is undefined

As you have probably noticed, "filebeat.key" is the value of "filebeat_ssl_key_file" and it is considered as an object, named "filebeat" which is undefined.

Adding a "is defined" will solve the problem.

**
In the line number 28 at the same file, we have: 
`when: filebeat_ssl_key_file and filebeat_ssl_certificate_file`
which does not fail
I suppose it is because of the "AND" operator. The and operator returns "true" or "false" which is completely acceptable for being used inside a condition. And apparently, this operator handles "string" values as "true". Therefore, one other possible fix for that line could be:

`- name: Ensure Filebeat SSL key pair directory exists.`
`  file:`
`    path: "{{ filebeat_ssl_dir }}"`
`    state: directory`
`  when: filebeat_ssl_key_file and "MAGMAG"`
`  tags: configure`

**Comment by manuasir** [comment] 2019-04-29 17:23
Hello @M-Golyani ,

Thanks for reporting this. We will evaluate the requested changes and will let you know when they're merged.

Regards

**Comment by rshad** [comment] 2019-07-03 16:17
Hi @M-Golyani,

It's my pleasure to assist you!

Regarding the error you reported, I tried to reproduce it, working with the release [`3.9`](https://github.com/wazuh/wazuh-ansible/tree/3.9) of `wazuh-ansible` repo. But I did not reach to get the same error or issue you faced.

--------------

#### My Attempt Details
##### Ansible Version
In my case, I'm using `ansible 2.8.1`
```
[rshad@localhost wazuh-ansible]$ ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rshad/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
***Requested Info***: *Please advice with ansible version you used when the error got produced*

##### Operating System image I used in my attempt
```ruby
[rshad@localhost wazuh-ansible]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[rshad@localhost wazuh-ansible]$
```
-------
#### Output of the execution of the problamatic task

Please find below the related task.

```ansible
name: Ensure Filebeat SSL key pair directory exists.
file:
  path: "{{ filebeat_ssl_dir }}"
  state: directory
when: filebeat_ssl_key_file
tags: configure
```

##### Output
```
TASK [/etc/ansible/roles/wazuh-ansible/roles/wazuh/ansible-filebeat : Ensure Filebeat SSL key pair directory exists.] **************************************************
```

##### Message 1
```
[DEPRECAstrikethrough textTION WARNING]: evaluating filebeat_create_config as a bare variable, this behavior will go away and you might need to add |bool to the expression in the
future. Also, see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

##### Message 2
```
[DEPRECATION WARNING]: evaluating filebeat_ssl_key_file as a bare variable, this behavior will go away and you might need to add |bool to the expression in the
future. Also, see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
skipping: [192.168.0.101]
```
---------
### Analysis
I think you're confused with the value of the variable `filebeat_ssl_key_file`  when you say:
> As you have probably noticed, "filebeat.key" is the value of "filebeat_ssl_key_file" and it is considered as an object, named "filebeat" which is undefined.

`filebeat_ssl_key_file` is a boolean variable which is used to decide to run the related task or not. So if it has the value `true` then the task `Ensure Filebeat SSL key pair directory exists` will be executed, in other cases which are represented by the value `false` then the task will be skipped.

Looking at this variable `filebeat_ssl_key_file` by following its appearences in all the files in the playbooks, roles, etc ..., I found the following:

`roles/wazuh-ansible/roles/wazuh/ansible-filebeat/README.md:  filebeat_ssl_key_file: ""
`

This is the path of the file where it's defined and as you can see, it has no value assigned. In this case, Ansible will not consider it as True neither as False and so the task will be skipped.

---------
**Warnings and Deprecation Messages**

In ***Message 1*** and ***Message 2***  and since Ansible was upgraded to 2.8.* version it changes the way to deal with boolean variables and it's advising to start using boolean pipe indicating the boolean value referenced in a conditional task. 

Imagine you have a boolean variable, called `run_actual_task` and you assign `true` as default value. Then in the task, you should put:

##### Explicitly Saying: Do Not Run this Task
`when: run_actual_task |bool  == false `

##### Explicitly Saying: Run this Task
`when: run_actual_task |bool  == true`

------ 
:confused: **Own Opinion**: Sincerely I see no need for such pipelining!

Please check [here](https://github.com/ansible/ansible/issues/53428) to know more about this change.

----
#### It would be great if you provide to us the following information

 1. Ansible Version you used when such error got produced.
 2. wazuh-ansible repo branch or release you ran when you faced such issue

Kind Regards,

*Rshad Zhran*

**Comment by rshad** [comment] 2019-08-05 07:34
Hi @M-Golyani,

Could you please advise if the provided information resolves the issue? And if not, could you please provide the requested information?

Kind regards,

Rshad

**Comment by manuasir** [comment] 2019-08-07 15:04
Hello @M-Golyani ,

Please, open a new issue whenever you may need this. This one will be closed due to inactivity.

Thanks for contributing

**Closed by manuasir** 2019-08-07 15:04 UTC
Labels: bug
