### ISSUE TITLE
elastic repo version mismatch between the add-repo & remove-repo tasks

### ISSUE THREAD

**Issue by M-Golyani** [wazuh/wazuh-ansible#192] opened 2019-06-19 15:55 UTC
Hi guys :)
In the stable branch, during the installation via ansible, when adding the elasticsearch repo in this file:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-elasticsearch/tasks/Debian.yml Line 21:
`- name: Debian/Ubuntu | Install Elastic repo`
`  apt_repository:`
**`    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'`**
`    state: present`
`    filename: 'elastic_repo'`
`    update_cache: true`

A version 6.x repo is added.
But later on, when removing the previously added repo, in this file:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-elasticsearch/tasks/RMDebian.yml Line 4:
`- name: Debian/Ubuntu | Removing Elasticsearch repository`
`  apt_repository:`
**`    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main`**
`    state: absent`

The repo of version 5.x is removed, which is probably not present already. This will probably not raise an error but will leave the system with a debian sources.list.d repo file of version 6.x which could cause unwanted updates ...

The same things for Kibana:
Adding V6.x:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-kibana/tasks/Debian.yml
Removing V5.x:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-kibana/tasks/RMDebian.yml

And the same thing for logstash:
Adding V6.x:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-logstash/tasks/Debian.yml
Removing V5.x:
https://github.com/wazuh/wazuh-ansible/blob/stable/roles/elastic-stack/ansible-logstash/tasks/RMDebian.yml

This is not the issue on the "master" branch.

**Comment by jm404** [comment] 2019-06-21 07:10
Hi @M-Golyani,

I checked `RMDebian.yml` and you are completely right, there is a mismatch in versions and the Wazuh repository should also be removed.

We are working on a fix on this and will let you know when we finish the testing and open the PR.

Thanks for reporting, community contributions are really appreciated.

Best regards,

Jose

**Comment by manuasir** [comment] 2019-06-21 10:29
Hi @M-Golyani ,

This was already implemented, the problem is that the `stable` branch wasn't updated so I just merged it. Every `Elastic` repository points to the `7.x` version. I'd also like to mention that since the adaptation to `Elastic 7`, the Logstash component is not used anymore.

Apologies for the inconveniences and don't hesitate to write another issue if you need it.

Cheers

**Closed by manuasir** 2019-06-21 10:29 UTC
